name: diff
channels:
  - conda-forge
dependencies:
  - aiohappyeyeballs=2.4.3
  - aiosignal=1.3.1
  - appnope=0.1.4
  - arrow-cpp=9.0.0
  - asttokens=2.4.1
  - async-timeout=4.0.3
  - attrs=24.2.0
  - aws-c-auth=0.7.8
  - aws-c-cal=0.6.9
  - aws-c-common=0.9.10
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.2
  - aws-c-http=0.7.15
  - aws-c-io=0.13.36
  - aws-c-mqtt=0.10.0
  - aws-c-s3=0.4.6
  - aws-c-sdkutils=0.1.13
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.25.0
  - aws-sdk-cpp=1.11.210
  - backcall=0.2.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.33.1
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - cffi=1.17.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.2
  - datasets=2.16.1
  - debugpy=1.8.5
  - decorator=5.1.1
  - diffusers=0.30.3
  - dill=0.3.7
  - executing=2.1.0
  - freetype=2.12.1
  - frozenlist=1.4.1
  - ftfy=6.2.3
  - gflags=2.2.2
  - glog=0.6.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - h2=4.1.0
  - hpack=4.0.0
  - huggingface_hub=0.25.1
  - hyperframe=6.0.1
  - ipykernel=6.29.5
  - ipython=8.12.2
  - jedi=0.19.1
  - jinja2=3.1.4
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20230802.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.10.1
  - libcxx=19.1.1
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libgoogle-cloud=2.12.0
  - libgrpc=1.59.3
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libopenblas=0.3.27
  - libpng=1.6.44
  - libprotobuf=4.24.4
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsqlite=3.46.1
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.7.0
  - libutf8proc=2.8.0
  - libuv=1.49.0
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=19.1.0
  - lz4-c=1.9.4
  - markupsafe=2.1.5
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multiprocess=0.70.15
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.1
  - nomkl=1.0
  - numpy=1.24.4
  - openjpeg=2.5.2
  - openssl=3.3.2
  - orc=1.9.2
  - packaging=24.1
  - pandas=2.0.3
  - parquet-cpp=1.5.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=9.0.0
  - pyarrow-hotfix=0.6
  - pycparser=2.22
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.8.19
  - python-tzdata=2024.2
  - python-xxhash=3.5.0
  - python_abi=3.8
  - pytorch=2.1.0
  - pytz=2024.2
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - re2=2023.09.01
  - readline=8.2
  - regex=2024.7.24
  - requests=2.32.3
  - setuptools=73.0.1
  - six=1.16.0
  - sleef=3.7
  - snappy=1.1.10
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xxhash=0.8.2
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - accelerate==0.34.2
      - aiohttp==3.10.9
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.5.0
      - argmaxtools==0.1.13
      - beartype==0.18.5
      - cattrs==24.1.0
      - click==8.1.7
      - click-help-colors==0.9.4
      - click-shell==2.1
      - contourpy==1.1.1
      - coremltools==8.0
      - cycler==0.12.1
      - diffusionkit==0.3.4
      - einops==0.8.0
      - exceptiongroup==1.2.2
      - facexlib==0.3.0
      - fairscale==0.4.13
      - fastapi==0.115.0
      - filelock==3.15.4
      - filterpy==1.4.5
      - fonttools==4.53.1
      - fsspec==2024.9.0
      - h11==0.14.0
      - huggingface-hub==0.24.6
      - idna==3.8
      - imageio==2.35.1
      - imaginairy==13.2.1
      - importlib-metadata==8.4.0
      - importlib-resources==6.4.4
      - iniconfig==2.0.0
      - invisible-watermark==0.2.0
      - jaxtyping==0.2.19
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - kornia==0.7.3
      - kornia-rs==0.1.5
      - lightning-utilities==0.11.7
      - llvmlite==0.41.1
      - matplotlib==3.7.5
      - mlx==0.17.2
      - multidict==6.1.0
      - numba==0.58.1
      - omegaconf==2.3.0
      - open-clip-torch==2.26.1
      - opencv-python==4.10.0.84
      - pluggy==1.5.0
      - protobuf==3.20.3
      - pyaml==24.7.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pyparsing==3.1.4
      - pytest==8.3.2
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==1.9.5
      - pywavelets==1.4.1
      - safetensors==0.4.5
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - sentencepiece==0.2.0
      - sniffio==1.3.1
      - starlette==0.38.6
      - sympy==1.13.2
      - tabulate==0.9.0
      - threadpoolctl==3.5.0
      - timm==1.0.9
      - tokenizers==0.13.3
      - tomli==2.0.1
      - torch==1.13.1
      - torchdiffeq==0.2.4
      - torchmetrics==1.4.2
      - torchvision==0.14.1
      - transformers==4.29.2
      - typeguard==4.3.0
      - urllib3==2.2.2
      - uvicorn==0.31.0
      - yarl==1.13.1
      - zipp==3.20.1
